/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as companies from "../companies.js";
import type * as dashboard_equityPie from "../dashboard/equityPie.js";
import type * as files from "../files.js";
import type * as helpers_ingestHelpers from "../helpers/ingestHelpers.js";
import type * as helpers_promptHelpers from "../helpers/promptHelpers.js";
import type * as helpers_utils from "../helpers/utils.js";
import type * as ingest_chunkers from "../ingest/chunkers.js";
import type * as ingest_embed from "../ingest/embed.js";
import type * as ingest_extract from "../ingest/extract.js";
import type * as meetingAgenda from "../meetingAgenda.js";
import type * as messages from "../messages.js";
import type * as notes from "../notes.js";
import type * as persons from "../persons.js";
import type * as records from "../records.js";
import type * as serve from "../serve.js";
import type * as tasks from "../tasks.js";
import type * as together from "../together.js";
import type * as users from "../users.js";
import type * as whisper from "../whisper.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  companies: typeof companies;
  "dashboard/equityPie": typeof dashboard_equityPie;
  files: typeof files;
  "helpers/ingestHelpers": typeof helpers_ingestHelpers;
  "helpers/promptHelpers": typeof helpers_promptHelpers;
  "helpers/utils": typeof helpers_utils;
  "ingest/chunkers": typeof ingest_chunkers;
  "ingest/embed": typeof ingest_embed;
  "ingest/extract": typeof ingest_extract;
  meetingAgenda: typeof meetingAgenda;
  messages: typeof messages;
  notes: typeof notes;
  persons: typeof persons;
  records: typeof records;
  serve: typeof serve;
  tasks: typeof tasks;
  together: typeof together;
  users: typeof users;
  whisper: typeof whisper;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
